linkorb/wiki-bundle

- Controller/WikiController.php
- Controller/WikiEventController.php
- Controller/WikiPageController.php
- composer.json
- composer.lock
> feat: integrate spaces project #3447

- composer.json
- composer.lock
> 3447 integrate spaces

- Repository/WikiEventRepository.php
- Repository/WikiPageRepository.php
- Repository/WikiRepository.php
> fix: support symfony new version #3447

- Controller/WikiPageController.php
> fix: support symfony 5 version #3447

- Controller/WikiPageController.php
> fix: support symfony 5 #3447

- Controller/WikiController.php
- Controller/WikiPageController.php
- Entity/Wiki.php
- Entity/WikiPage.php
- Form/WikiPageContentType.php
- Form/WikiPageType.php
- Form/WikiType.php
- Repository/WikiPageRepository.php
- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/advanced.html.twig
- Resources/views/wiki_page/edit.html.twig
- Resources/views/wiki_page/index.html.twig
- Resources/views/wiki_page/view.html.twig
- Services/WikiPageService.php
- Twig/WikiExtension.php
> 4365 pages enhancements

- Resources/views/wiki_page/index.html.twig
> feat: page enhancements #4365

- Command/WikiExportCommand.php
- Command/WikiImportCommand.php
- Controller/ApiController.php
- Controller/WikiController.php
- Controller/WikiPageController.php
- Repository/WikiPageRepository.php
- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/advanced.html.twig
- Resources/views/wiki_page/edit.html.twig
- Resources/views/wiki_page/view.html.twig
- Services/WikiEventService.php
- Services/WikiPageService.php
- Services/WikiService.php
- Twig/WikiExtension.php
- composer.json
- composer.lock
> 4439 enhancements

- Services/WikiService.php
> feat: wiki json export modification #4439

- Command/WikiExportCommand.php
> fix: export issue #4439

- Services/WikiService.php
> perf: enhance wiki page export and import #4439

- Services/WikiService.php
> perf: wiki export import enhancement #4439

- Services/WikiService.php
> fix: wkik import issue #4439

- Services/WikiService.php
> fix: wiki import  #4439

- Controller/WikiController.php
- Controller/WikiEventController.php
- Controller/WikiPageController.php
- Services/WikiService.php
> perf: wiki permission enhancements

- Controller/WikiController.php
- Controller/WikiPageController.php
- Form/WikiPageType.php
- Form/WikiSearchType.php
- Resources/views/base.wiki.html.twig
- Resources/views/wiki/search.html.twig
- Resources/views/wiki_page/advanced.html.twig
> perf:  wiki enhancement #4550

- Form/WikiSearchType.php
> perf: wiki enhancement #4550

- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/view.html.twig
> perf:  markdown extra enhancements #5257

- Controller/ApiController.php
- README.md
- Resources/views/base.wiki.html.twig
> feat: api wiki import #5903

- composer.json
> fix: composer package suport symfony 6 #0000

- Controller/WikiController.php
- Controller/WikiPageController.php
- Resources/views/base.wiki.html.twig
- Services/WikiService.php
- composer.json
> perf:  symfony6 demo app support enhancement #6495

- Services/WikiService.php
> perf: markdown table extension #7209

- Services/WikiService.php
> fix: undefined variable content #7406

- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/view.html.twig
> chore: set image maxwith on wiki page #8240

- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/view.html.twig
> chore: wiki page content max width #0000

- Resources/views/base.html.twig
- Resources/views/base.wiki.html.twig
> chore: page image max width #8240

- .gitignore
- Controller/WikiController.php
- Controller/WikiPageController.php
- Entity/Wiki.php
- README.md
- Resources/views/base.wiki.html.twig
- Resources/views/wiki_page/read_only.html.twig
- Services/WikiService.php
> git push and pull integration #8338 

- README.md
> chore: update readme file #8338

- Controller/WikiEventController.php
- Controller/WikiPageController.php
- Entity/WikiEvent.php
- Repository/WikiEventRepository.php
- Resources/views/base.wiki.html.twig
- Resources/views/wiki_event/index.html.twig
- Resources/views/wiki_event/list.html.twig
- Resources/views/wiki_event/page_event.html.twig
- Resources/views/wiki_event/view.html.twig
- Services/WikiEventService.php
- Services/WikiService.php
> perf: track page title content changes in wiki event #8553

- Controller/WikiEventController.php
- Resources/views/wiki_event/view.html.twig
> perf: enhance track page title content chagnes in wiki event #8553
